backend:
  name: github
  repo: generally-rich/23opentabs
  branch: main
  base_url: https://auth.23opentabs.com
  auth_endpoint: /oauth

media_folder: "/static/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/english/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
